apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jnxmsuvbh-go 
  janus-idp.io/tekton: jnxmsuvbh-go
  backstage.io/kubernetes-id: jnxmsuvbh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jnxmsuvbh-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml